# Configuración para Render
services:
  # Backend API
  - type: web
    name: chat-fj-api
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn src.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: moonshotai/kimi-k2-instruct-0905

      - key: EMBEDDING_MODEL
        value: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
      - key: PINECONE_ENV
        value: us-east-1
      - key: PINECONE_INDEX_NAME
        value: chatfj-legal-index
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: PINECONE_API_KEY
        sync: false

    
  # Frontend
  - type: web
    name: chat-fj-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: chat-fj-api
          property: url

