"""
Configuración del sistema
"""

from .constants import (
    POPULAR_CR_INSTITUTIONS,
    POPULAR_CR_INSTITUTIONS_TEXT,
    LEGAL_CATEGORIES,
    CATEGORY_TO_LAWS,
    LLM_CONFIG,
    CACHE_CONFIG,
    SEARCH_CONFIG,
    UI_CONFIG,
    AMBIGUOUS_TERMS,
    CONTACT_PLACEHOLDER,
)

__all__ = [
    'POPULAR_CR_INSTITUTIONS',
    'POPULAR_CR_INSTITUTIONS_TEXT',
    'LEGAL_CATEGORIES',
    'CATEGORY_TO_LAWS',
    'LLM_CONFIG',
    'CACHE_CONFIG',
    'SEARCH_CONFIG',
    'UI_CONFIG',
    'AMBIGUOUS_TERMS',
    'CONTACT_PLACEHOLDER',
]
