name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *' # Cada 10 minutos (Render duerme a los 15, esto es más seguro)
  workflow_dispatch: # Permite ejecutar manualmente desde GitHub Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend Helper
        run: |
          echo "Pinging..."
          # Usamos curl para hacer una petición HEAD ligera al endpoint de salud
          curl -I https://chatfj-m63k.onrender.com/health
          echo "Done."
